### ISSUE TITLE
[1.12.1] Some missing textures

### ISSUE THREAD

**Issue by ghost** [Liahim85/SaltyMod_1.10.2#1]
I hope this is the right repository.
Some textures are missing (hemaglobin et al) see image.

![2017-09-12_10 55 42](https://user-images.githubusercontent.com/22838247/30317635-f5f729cc-97aa-11e7-8c7f-edf4caa7a129.png)

**Comment by Liahim85** [comment]
Hello!
I see that all standard items are seen normally.
All items with missing textures should be visible only if necessary mods such as Biomes'O Plenty or Twilight Forest are present.
In theory, without these mods items did not even have to register.
If you see these items, then you are viewing them not in vanilla inventory ... Either this is really a bug.

**Comment by ghost** [comment]
This is a screenshot from JEI. I also have BoP installed.

**Comment by Liahim85** [comment]
OK. Thank you for message.
I'll check it later. After the Misty World update.

**Comment by Sunconure11** [comment]
I can confirm the issue is still present.

![screenshot 2017-11-11 19 06 52](https://user-images.githubusercontent.com/5614902/32694651-87e87dbc-c713-11e7-903e-380057d3226d.png)

**Comment by Nimflora** [comment]
Issue is still present.

**Comment by Liahim85** [comment]
Update for 1.12
