### ISSUE TITLE
Evaporator Automation Wastes Fuel

### ISSUE THREAD

**Issue by mrgrim** [Liahim85/SaltyMod_1.10.2#10]
Automating the evaporator requires keeping a piston extended over the evaporator between two water sources until the evaporator has complete producing 1 pinch of salt. The piston must retracted for 10 game ticks minimum for a new water source to form above the evaporator.

Retracting the piston can be done on a timer to minimize delay, or the pinch of salt being extracted can be detected by a comparator adding additional delay to the circuit. It seems there's no way to automate that doesn't waste, at a minimum, 10 ticks of fuel, and this is already an extremely fuel expensive process.

**Comment by Liahim85** [comment]
I think you're right )
But you always have the opportunity to go to the mines )
