### ISSUE TITLE
[1.12.2] Food give absurd amounts of saturation

### ISSUE THREAD

**Issue by Lykrast** [Liahim85/SaltyMod_1.10.2#3]
All foods added by this mod have absurd amounts of saturation, as seen here using Apple Skin to show the values :
![image](https://user-images.githubusercontent.com/8684850/34915889-95558a60-f92e-11e7-991a-41e0b18c0deb.png)
![image](https://user-images.githubusercontent.com/8684850/34915892-9b7a6d7a-f92e-11e7-8080-0c9fc680acdc.png)

This is probably due to the way saturation in ItemFood is multiplied by the hunger restored and that you weren't aware of it (and also that saturation is not visible in game to verify values unless you have something like AppleSkin).

**Comment by Liahim85** [comment]
Yes, thank you, I know about this and planned to fix it in the next update. As soon as I have time, I will do it.

**Comment by Liahim85** [comment]
Update for 1.12
