### ISSUE TITLE
Fermented Mushgloom Recipe Not Working

### ISSUE THREAD

**Issue by Nimflora** [Liahim85/SaltyMod_1.10.2#5]
![screen shot 2018-01-26 at 1 20 25 pm](https://user-images.githubusercontent.com/30032372/35454375-c6fe161a-029b-11e8-82ee-78e3842f6b5c.png)
![screen shot 2018-01-26 at 1 20 35 pm](https://user-images.githubusercontent.com/30032372/35454378-c9d33b18-029b-11e8-845c-b4f90ed91698.png)
Missing textures/files and uncraftable potion?

**Comment by Liahim85** [comment]
Thanks! Fixed.
