### ISSUE TITLE
Salt Lake Beds only generating at Y=~64

### ISSUE THREAD

**Issue by PCSpinner** [Liahim85/SaltyMod_1.10.2#7]
SaltyMod 1.12.2_f
Forge 14.23.5.2768

When altering the height of the world (via BiomeTweaker) salt beds only generate in ravines that are open to the sky and have a bottom at y=64. 

It would be nice to have a config option to change the level the generate at. 
Or maybe an option to have them generate anywhere that can see the sky.

**Comment by Liahim85** [comment]
Done!
