### ISSUE TITLE
Hopper Extracts Fuel From Evaporator

### ISSUE THREAD

**Issue by mrgrim** [Liahim85/SaltyMod_1.10.2#9]
Subject basically says it all. It forces you to add an item filter circuit to pull pinches of salt only from the evaporator. It would make more sense for the evaporator to act like a furnace in this regard and not allow fuel to be removed via a hopper.

**Comment by Liahim85** [comment]
Yes, I know about this bug, but I could not fix it. I think this is a forge problem, since the code itself is identical to the furnace.

**Comment by mrgrim** [comment]
There's definitely shenanigans going on, but it's not a bug. Forge seems to have some sort of "capabilities" system that overrides vanilla hopper code. Without overriding the necessary functions, the `TileEntityExtractor` class is inheriting a side agnostic handler from `TileEntityLockable`.

This is an excerpt from the Forge additions to `TileEntityFurnace`:

```java
    net.minecraftforge.items.IItemHandler handlerTop = new net.minecraftforge.items.wrapper.SidedInvWrapper(this, net.minecraft.util.EnumFacing.UP);
    net.minecraftforge.items.IItemHandler handlerBottom = new net.minecraftforge.items.wrapper.SidedInvWrapper(this, net.minecraft.util.EnumFacing.DOWN);
    net.minecraftforge.items.IItemHandler handlerSide = new net.minecraftforge.items.wrapper.SidedInvWrapper(this, net.minecraft.util.EnumFacing.WEST);

    @SuppressWarnings("unchecked")
    @Override
    public <T> T getCapability(net.minecraftforge.common.capabilities.Capability<T> capability, @javax.annotation.Nullable net.minecraft.util.EnumFacing facing)
    {
        if (facing != null && capability == net.minecraftforge.items.CapabilityItemHandler.ITEM_HANDLER_CAPABILITY)
            if (facing == EnumFacing.DOWN)
                return (T) handlerBottom;
            else if (facing == EnumFacing.UP)
                return (T) handlerTop;
            else
                return (T) handlerSide;
        return super.getCapability(capability, facing);
    }
```

It appears you'll need to replicate this and/or simply return a null handler to default to vanilla code, I think.

**Comment by Liahim85** [comment]
Thank! I will try to do it.

**Comment by Liahim85** [comment]
Done!
